general:
  downloads: /home/fjasensi/PyYt

paths:
  sci: science
  tech: technology
  math: maths
  bd: big_data
  df: default
  ai: artificial_intelligence
  eng: english
  tut: tutorials
  dev: development
  cs: computer_science
  mu: music
